spring:
  application:
    name: cdr
  datasource:
    url: jdbc:h2:file:/temp/data/testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      settings:
        trace: true
      enabled: true
      path: /h2-console